### PR TITLE
Ensure that target.ip is used when a hostname is not provided

### LINKED ISSUE #46: checker:event_handler fails on a "remove" event
When the `self.targets` table is [populated](https://github.com/Kong/lua-resty-healthcheck/blob/master/lib/resty/healthcheck.lua#L1072), the code uses `hostname or ip` in case the user did not provide a hostname. However, when the same table is accessed for a ["remove" event](https://github.com/Kong/lua-resty-healthcheck/blob/master/lib/resty/healthcheck.lua#L1037), the code simply refers to `target_found.hostname`, which results in an attempt to access a `nil` key.

Adding: `or target_found.ip` to that key should suffice.

### PR DESCRIPTION
**Pull request by timmysilv**
If the caller did not provide a hostname, this ensures that the `remove` code in the callback does not reference a nil-key in a table.

Fixes #46

### CODE REVIEW

**Comment by locao** [comment]
Hi @timmysilv! Thanks for your submission! Could you provide an automated test for that fix, please? This way we know this issue won't ever come back.

Also, you can finish your Pull Request description with "Fix: #n", so when the PR is merged the issue is automatically considered fixed.

**Comment by timmysilv** [comment]
Had some trouble with `make install`, patched that as well and rebased. Lmk if you'd prefer I separate this into 2 different PRs, or take some other action before this can be merged. Thanks!

**Comment by timmysilv** [comment]
I'm not sure how to trigger another travis build, but the error seems irrelevant to my latest change, which was another instance of `target.hostname` causing a table to refer to the nil-key (this time in `new()`).

**Comment by Tieske** [comment]
Thank you, merged with manually updated commits.

**Pull request merged**
